apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: Application to shorten long URLs
  annotations:
    github.com/project-slug: https://github.com/{{ values.githubOwner }}/${{ values.name }}
spec:
  type: service
  lifecycle: production
  owner: rohitratannagar
